# Default
Hierarchy00:
  task_class_names: [[TaskBaseCoMTracking, TaskBodyCoMTracking, TaskBaseOrientation], [TaskJointsReference]]
  task_ids: [[TaskBaseCoMTracking, TaskBodyCoMTracking, TaskBaseOrientation], [TaskJointsReference]]
  TaskBaseOrientation:
    gain: 1
    k_orientation_gain: 1
  TaskBodyCoMTracking:
    gain: 1
    k_position_gain: 1
    axis_flag: 7
  TaskBaseCoMTracking:
    gain: 1
    k_position_gain: 1
  TaskJointsReference:
    gain: 1
    k_position_gain: 0.3
    joint_angles_reference: [-0.01, -0.04, 0, 0, -0.2, 1.57, 0.12, -1.2217007, -0.52345699, 0, 1.57, -0.12, 1.2217007, 0.52345699, 0]


# Fixed head and arms
Hierarchy01:
  task_class_names: [[TaskBaseCoMTracking, TaskBaseOrientation, TaskFixArms, TaskFixHead, TaskJointsBounds], [TaskBodyCoMTracking]]
  task_ids: [[TaskBaseCoMTracking, TaskBaseOrientation, TaskFixArms, TaskFixHead, TaskJointsBounds], [TaskBodyCoMTracking]]
  TaskBaseOrientation:
    gain: 1
    k_orientation_gain: 1
  TaskBaseCoMTracking:
    gain: 1
    k_position_gain: 1
  TaskFixArms:
    {}
  TaskFixHead:
    {}
  TaskJointsBounds:
    {}
  TaskBodyCoMTracking:
    gain: 1
    k_position_gain: 1
    axis_flag: 7


# Base motion on the second level
Hierarchy02:
  task_class_names: [[TaskBodyCoMTracking], [TaskBaseCoMTracking, TaskBaseOrientation, TaskJointsReference]]
  task_ids: [[TaskBodyCoMTracking], [TaskBaseCoMTracking, TaskBaseOrientation, TaskJointsReference]]
  TaskBaseOrientation:
    gain: 1
    k_orientation_gain: 1
  TaskBodyCoMTracking:
    gain: 1
    k_position_gain: 1
    axis_flag: 7
  TaskBaseCoMTracking:
    gain: 1
    k_position_gain: 1
  TaskJointsReference:
    gain: 1
    k_position_gain: 0.3
    joint_angles_reference: [-0.01, -0.04, 0, 0, -0.2, 1.57, 0.12, -1.2217007, -0.52345699, 0, 1.57, -0.12, 1.2217007, 0.52345699, 0]


# Fixed arms
Hierarchy03:
  task_class_names: [[TaskBaseCoMTracking, TaskBaseOrientation, TaskFixArms, TaskBodyCoMTracking], [TaskJointsReference]]
  task_ids: [[TaskBaseCoMTracking, TaskBaseOrientation, TaskFixArms, TaskBodyCoMTracking], [TaskJointsReference]]
  TaskBaseOrientation:
    gain: 1
    k_orientation_gain: 1
  TaskBaseCoMTracking:
    gain: 1
    k_position_gain: 1
  TaskFixArms:
    {}
  TaskBodyCoMTracking:
    gain: 1
    k_position_gain: 1
    axis_flag: 7
  TaskJointsReference:
    gain: 1
    k_position_gain: 0.3
    joint_angles_reference: [-0.01, -0.04, 0, 0, -0.2, 1.57, 0.12, -1.2217007, -0.52345699, 0, 1.57, -0.12, 1.2217007, 0.52345699, 0]


# damp joint velocities instead of maintaining reference configuration + fixed arms
Hierarchy04:
  task_class_names: [[TaskBaseCoMTracking, TaskBodyCoMTracking, TaskBaseOrientation, TaskFixArms], [TaskZeroVariables]]
  task_ids: [[TaskBaseCoMTracking, TaskBodyCoMTracking, TaskBaseOrientation, TaskFixArms], [TaskJointsDamping]]
  TaskBaseOrientation:
    gain: 1
    k_orientation_gain: 1
  TaskBodyCoMTracking:
    gain: 1
    k_position_gain: 1
    axis_flag: 7
  TaskBaseCoMTracking:
    gain: 1
    k_position_gain: 1
  TaskFixArms:
    {}
  TaskJointsDamping:
    gain: 1
    variables_id: joints_vel
