# Velocity reference
Hierarchy00:
  task_class_names: [[TaskBaseVelocityBounds, TaskBodyPositionBounds, TaskCoPPositionBounds, TaskBaseAccelerationBounds], [TaskBaseVelocityReference, TaskBaseJerkMinimization, TaskBodyJerkMinimization, TaskCoPCentering]]
  task_ids: [[TaskBaseVelocityBounds, TaskBodyPositionBounds, TaskCoPPositionBounds, TaskBaseAccelerationBounds], [TaskBaseVelocityReference, TaskBaseJerkMinimization, TaskBodyJerkMinimization, TaskCoPCentering]]
  TaskBaseAccelerationBounds:
    gain: 0
  TaskCoPPositionBounds:
    gain: 0
  TaskBodyPositionBounds:
    gain: 0
  TaskBaseVelocityBounds:
    {}
  TaskCoPCentering:
    gain: 0.707106781186548
  TaskBaseJerkMinimization:
    gain: 0.0223606797749979
  TaskBaseVelocityReference:
    gain: 1
  TaskBodyJerkMinimization:
    gain: 0.0223606797749979
    variables_id: body_pos


# Base position reference
Hierarchy01:
  task_class_names: [[TaskBaseVelocityBounds, TaskBodyPositionBounds, TaskCoPPositionBounds, TaskBaseAccelerationBounds], [TaskBasePositionReference, TaskBaseJerkMinimization, TaskBodyJerkMinimization, TaskCoPCentering]]
  task_ids: [[TaskBaseVelocityBounds, TaskBodyPositionBounds, TaskCoPPositionBounds, TaskBaseAccelerationBounds], [TaskBasePositionReference, TaskBaseJerkMinimization, TaskBodyJerkMinimization, TaskCoPCentering]]
  TaskBaseAccelerationBounds:
    gain: 0
  TaskCoPPositionBounds:
    gain: 0
  TaskBodyPositionBounds:
    gain: 0
  TaskBaseVelocityBounds:
    {}
  TaskCoPCentering:
    gain: 0.707106781186548
  TaskBaseJerkMinimization:
    gain: 0.0223606797749979
  TaskBasePositionReference:
    gain: 0.707106781186548
  TaskBodyJerkMinimization:
    gain: 0.0223606797749979
    variables_id: body_pos
