ModelState:
  base_state:
    position: [0, 0, 0.125564931735602]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
    rpy: [0, 0, 0]
    angular_velocity: [0, 0, 0]
    angular_acceleration: [0, 0, 0]
  body_state:
    position: [-0.00656061094036387, 0, 7.50001340031501e-01]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
  base_mass: 16.34234
  body_mass: 12.3389
