ModelState:
  base_state:
    position: [0, 0, 0.125564931735602]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
    rpy: [0, 0, 0]
    angular_velocity: [0, 0, 0]
    angular_acceleration: [0, 0, 0]
  body_state:
    position: [-0.00671291567566885, 0, 0.763104597149514]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
  base_mass: 16.34234
  body_mass: 12.3389
