RobotParameters:
  base_radius: 0.7
  max_nominal_base_velocity: 0.5
  max_nominal_base_acceleration: 1
  max_base_velocity: 1.4
  max_base_acceleration: 1.7
  body_bounds:
    cols: 2
    rows: 2
    data: [-0.06, 0.06, -0.03, 0.03]
